### ISSUE TITLE
Whisper Error

### ISSUE THREAD

**Issue by Assia55** [rudymohammadbali/Whisper-Transcriber#12]
![image](https://github.com/user-attachments/assets/c1c2a8ad-4bb1-48b9-8ecb-3a0befbda259)

I try `pip install numpy` and `pip install --upgrade numpy` still not work

**Comment by Assia55** [comment]
the full error :
```sh
from whisper import load_model
  File "c:\Users\app_test\whisper\__init__.py", line 8, in <module>
    import torch
  File "c:\Users\app_test\Env\Lib\site-packages\torch\__init__.py", line 2120, in <module>
    from torch._higher_order_ops import cond
  File "c:\Users\app_test\Env\Lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "c:\Users\app_test\Env\Lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "c:\Users\app_test\Env\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "c:\Users\app_test\Env\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
c:\Users\app_test\Env\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
c:\Users\app_test\whisper\__init__.py:146: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
Traceback (most recent call last):
  File "c:\Users\app_test\test.py", line 3, in <module>
    model = load_model("base")
            ^^^^^^^^^^^^^^^^^^
  File "c:\Users\app_test\whisper\__init__.py", line 154, in load_model
    model.set_alignment_heads(alignment_heads)
  File "c:\Users\app_test\whisper\model.py", line 251, in set_alignment_heads
    mask = torch.from_numpy(array).reshape(
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available

```

**Comment by rudymohammadbali** [comment]
You have to install numpy version: 1.26.2

```shell

pip install numpy==1.26.2

```

Did you install requirements from requirements.txt file?

**Comment by Assia55** [comment]
Thank you, **the problem is solved**
but i still get this message in console :
```sh
FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
```

**Comment by rudymohammadbali** [comment]
This is pytorch warning don't worry about it!
