### ISSUE TITLE
Traceback error cant start transcribing

### ISSUE THREAD

**Issue by Th3EvilGod** [rudymohammadbali/Whisper-Transcriber#7]
Audio Recognition started...
Exception in thread Thread-5 (start_transcribing):
Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\[username]\Desktop\Software\Whisper-Transcriber-main\src\ui\transcribe.py", line 205, in start_transcribing
    result = transcriber.audio_recognition(cancel_func=check_signal)
  File "C:\Users\[username]\Desktop\Software\Whisper-Transcriber-main\src\logic\transcriber.py", line 40, in audio_recognition
    _, probs = self.load_model.detect_language(mel)
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\[username]\Desktop\Software\Whisper-Transcriber-main\src\whisper\decoding.py", line 52, in detect_language
    mel = model.encoder(mel)
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\[username]\Desktop\Software\Whisper-Transcriber-main\src\whisper\model.py", line 162, in forward
    x = F.gelu(self.conv1(x))
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\[username]\Desktop\Software\Whisper-Transcriber-main\src\whisper\model.py", line 48, in _conv_forward
    return super()._conv_forward(
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [1280, 128, 3], expected input[1, 80, 3000] to have 128 channels, but got 80 channels instead

**Comment by Th3EvilGod** [comment]
@iamironman0 any progress on this? Transcriber doesnt work.

**Comment by iamironman0** [comment]
You have problem with pytorch

**Comment by iamironman0** [comment]
check it's version if it match in requirements (setup.py)

**Comment by Th3EvilGod** [comment]
i forced your requirements list and got this error.

```
ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement torch==2.1.1+cu118 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0)
ERROR: No matching distribution found for torch==2.1.1+cu118
```

**Comment by iamironman0** [comment]
Which python version do you use?

**Comment by Th3EvilGod** [comment]
Python 3.10.11

**Comment by iamironman0** [comment]
try use 3.9 with virtualenv

**Comment by Th3EvilGod** [comment]
Nothing changed. I am still getting the sane traceback error

**Comment by iamironman0** [comment]
Do even have a GPU with cuda?

**Comment by Th3EvilGod** [comment]
3080Ti

**Comment by rudymohammadbali** [comment]
Sorry for late response, hmm can't find the where the issue is without more details, do you installed GPU drivers? Try do some searching
